export class Movilidad {
    idCliente:string;
    idMovilidad:string;
    fechaEvento:Date;
    fechaSolicitud:Date;
    destino:string;
    nocheAlojamiento:string;
    tipoAcomodacion:string;
    transporte:string;
    alimentacion:string;
    acompanamientoGuia:string;
    seguroViaje:string;
    organizacionAgenda:string;
    visitaTecnica:string;
    costoEntrada:string;
    objervacion:string;
    tipoHotel:string;
    refrigerio:string;
    estado:string;
}
